@extends('layouts.app')
@section('title','Loans')
@section('page-title','Loans')
@section('page-subtitle','Track money you lend and money you borrow.')
@section('content')
<div class="row g-3 mb-4"><div class="col-md-6"><div class="surface-card stat-card"><div class="stat-icon"><i class="bi bi-arrow-down-left"></i></div><div class="stat-label">You will receive</div><div class="stat-value text-success" id="loanGivenTotal">Rs 0</div></div></div><div class="col-md-6"><div class="surface-card stat-card"><div class="stat-icon"><i class="bi bi-arrow-up-right"></i></div><div class="stat-label">You have to pay</div><div class="stat-value text-danger" id="loanTakenTotal">Rs 0</div></div></div></div>
<div class="page-actions justify-content-between"><select class="form-select w-auto" id="loanDirectionFilter"><option value="">All loans</option><option value="given">Loans given</option><option value="taken">Loans taken</option></select><button class="btn btn-primary" id="newLoan"><i class="bi bi-plus-lg me-2"></i>New loan</button></div>
<div class="surface-card table-card"><div class="table-responsive"><table class="table"><thead><tr><th>Person</th><th>Direction</th><th>Principal</th><th>Outstanding</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody id="loanRows"></tbody></table></div></div>

<div class="modal fade" id="loanModal"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" id="loanForm"><div class="modal-header"><h5 class="modal-title">New loan</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body">
<div class="row g-3"><div class="col-md-6"><label class="form-label">Direction</label><select class="form-select" name="direction"><option value="given">I am giving money</option><option value="taken">I am taking money</option></select></div><div class="col-md-6"><label class="form-label">Person</label><select class="form-select" name="person_id" required></select></div></div>
<div class="mt-3"><label class="form-label">Money account</label><select class="form-select" name="account_id" required></select></div>
<div class="row g-3 mt-0"><div class="col-md-6"><label class="form-label">Principal</label><input class="form-control" name="principal" type="number" min="0.01" step="0.01" required></div><div class="col-md-6"><label class="form-label">Start date</label><input class="form-control" name="start_date" type="date" value="{{ now()->toDateString() }}" required></div></div>
<div class="row g-3 mt-0"><div class="col-md-6"><label class="form-label">Due date</label><input class="form-control" name="due_date" type="date"></div><div class="col-md-6"><label class="form-label">Interest rate %</label><input class="form-control" name="interest_rate" type="number" min="0" step="0.01" value="0"></div></div>
<div class="row g-3 mt-0"><div class="col-md-6"><label class="form-label">Interest type</label><select class="form-select" name="interest_type"><option value="none">None</option><option value="simple">Simple</option><option value="fixed">Fixed</option></select></div><div class="col-md-6"><label class="form-label">Title</label><input class="form-control" name="title"></div></div>
<div class="mt-3"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div>
</div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Create loan</button></div></form></div></div>

<div class="modal fade" id="repayModal"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" id="repayForm"><div class="modal-header"><h5 class="modal-title">Record repayment</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="loan_id"><div class="mb-3"><label class="form-label">Account</label><select class="form-select" name="account_id" required></select></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Principal</label><input class="form-control" name="principal_amount" type="number" min="0.01" step="0.01" required></div><div class="col-md-6"><label class="form-label">Interest</label><input class="form-control" name="interest_amount" type="number" min="0" step="0.01" value="0"></div></div><div class="mt-3"><label class="form-label">Paid on</label><input class="form-control" name="paid_at" type="date" value="{{ now()->toDateString() }}" required></div><div class="mt-3"><label class="form-label">Description</label><input class="form-control" name="description"></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save repayment</button></div></form></div></div>
@endsection
@push('scripts')
<script>
(()=>{const M=MyLedger,body=document.querySelector('#loanRows'),form=document.querySelector('#loanForm'),repay=document.querySelector('#repayForm');let loans=[],accounts=[],people=[];async function refs(){[accounts,people]=await Promise.all([M.request('/ajax/accounts'),M.request('/ajax/people')]);M.fillSelect(form.account_id,accounts);M.fillSelect(repay.account_id,accounts);M.fillSelect(form.person_id,people,{placeholder:'Select person'});}async function load(){const d=document.querySelector('#loanDirectionFilter').value;try{loans=await M.request('/ajax/loans'+(d?'?direction='+d:''));document.querySelector('#loanGivenTotal').textContent=M.money(loans.filter(x=>M.typeValue(x.direction)==='given'&&x.status==='active').reduce((s,x)=>s+Number(x.outstanding_principal),0));document.querySelector('#loanTakenTotal').textContent=M.money(loans.filter(x=>M.typeValue(x.direction)==='taken'&&x.status==='active').reduce((s,x)=>s+Number(x.outstanding_principal),0));body.innerHTML=loans.length?loans.map(l=>`<tr><td><div class="fw-semibold">${M.esc(l.person?.name||'')}</div><div class="small text-secondary">${M.esc(l.title||'')}</div></td><td><span class="badge ${M.typeValue(l.direction)==='given'?'text-bg-success':'text-bg-warning'}">${M.typeValue(l.direction)==='given'?'Given':'Taken'}</span></td><td>${M.money(l.principal)}</td><td class="fw-semibold">${M.money(l.outstanding_principal)}</td><td>${M.date(l.due_date)}</td><td>${M.esc(l.status)}</td><td class="text-end">${l.status==='active'?`<button class="btn btn-sm btn-outline-primary repay" data-id="${l.id}">Repay</button>`:''}</td></tr>`).join(''):'<tr><td colspan="7"><div class="empty-state"><i class="bi bi-cash-stack"></i>No loans found.</div></td></tr>';}catch(e){M.toast(e.message,'danger')}}document.querySelector('#loanDirectionFilter').onchange=load;document.querySelector('#newLoan').onclick=()=>{form.reset();form.start_date.value='{{ now()->toDateString() }}';refs().then(()=>M.modal('loanModal'))};body.onclick=e=>{const b=e.target.closest('.repay');if(!b)return;const loan=loans.find(x=>String(x.id)===b.dataset.id);repay.reset();repay.loan_id.value=loan.id;repay.principal_amount.value=loan.outstanding_principal;repay.paid_at.value='{{ now()->toDateString() }}';refs().then(()=>M.modal('repayModal'))};form.onsubmit=async e=>{e.preventDefault();try{await M.request('/ajax/loans',{method:'POST',body:JSON.stringify(M.payload(form))});M.modal('loanModal','hide');M.toast('Loan recorded.');load()}catch(err){M.errors(form,err)}};repay.onsubmit=async e=>{e.preventDefault();const d=M.payload(repay),id=d.loan_id;delete d.loan_id;try{await M.request(`/ajax/loans/${id}/repay`,{method:'POST',body:JSON.stringify(d)});M.modal('repayModal','hide');M.toast('Repayment recorded.');load()}catch(err){M.errors(repay,err)}};Promise.all([refs(),load()])})();
</script>
@endpush
