@extends('layouts.app')
@section('title','Settings')
@section('page-title','Settings')
@section('page-subtitle','Profile, preferences, security and data export.')
@section('content')
<div class="row g-3">
    <div class="col-xl-7">
        <section class="surface-card mb-3"><div class="card-header-clean"><h2>Profile</h2></div><div class="card-body-clean"><form id="profileForm"><div class="row g-3"><div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" value="{{ auth()->user()->name }}" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" name="email" type="email" value="{{ auth()->user()->email }}" required></div></div><div class="text-end mt-3"><button class="btn btn-primary">Save profile</button></div></form></div></section>
        <section class="surface-card mb-3"><div class="card-header-clean"><h2>Preferences</h2></div><div class="card-body-clean"><form id="settingsForm"><div class="row g-3"><div class="col-md-4"><label class="form-label">Theme</label><select class="form-select" name="theme"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></div><div class="col-md-4"><label class="form-label">Locale</label><input class="form-control" name="locale" value="en" maxlength="10"></div><div class="col-md-4"><label class="form-label">Daily reminder</label><input class="form-control" name="daily_reminder_time" type="time"></div></div><div class="text-end mt-3"><button class="btn btn-primary">Save preferences</button></div></form></div></section>
        <section class="surface-card mb-3"><div class="card-header-clean"><h2>Change password</h2></div><div class="card-body-clean"><form id="passwordForm"><div class="mb-3"><label class="form-label">Current password</label><input class="form-control" type="password" name="current_password" required></div><div class="row g-3"><div class="col-md-6"><label class="form-label">New password</label><input class="form-control" type="password" name="password" required></div><div class="col-md-6"><label class="form-label">Confirm new password</label><input class="form-control" type="password" name="password_confirmation" required></div></div><div class="text-end mt-3"><button class="btn btn-primary">Update password</button></div></form></div></section>
        <section class="surface-card"><div class="card-header-clean"><h2>Recent accounting activity</h2></div><div class="card-body-clean" id="auditList"><div class="small text-secondary">Loading audit history…</div></div></section>
    </div>
    <div class="col-xl-5">
        <section class="surface-card mb-3"><div class="card-header-clean"><h2>Data & backup</h2></div><div class="card-body-clean"><p class="small text-secondary">Export a complete JSON backup or your transaction history as CSV.</p><div class="d-grid gap-2"><a class="btn btn-outline-secondary" href="{{ route('exports.backup') }}"><i class="bi bi-download me-2"></i>Download full backup</a><a class="btn btn-outline-secondary" href="{{ route('exports.transactions') }}"><i class="bi bi-filetype-csv me-2"></i>Export transactions CSV</a></div></div></section>
        <section class="surface-card"><div class="card-header-clean"><h2>Web security</h2></div><div class="card-body-clean"><div class="d-flex gap-3"><div class="account-icon"><i class="bi bi-shield-lock"></i></div><div><div class="fw-semibold">Session protected</div><p class="small text-secondary mb-0 mt-1">MyLedger uses Laravel session authentication, hashed passwords and CSRF protection for browser actions. Always use HTTPS in production.</p></div></div></div></section>
    </div>
</div>
@endsection
@push('scripts')
<script>
(async()=>{const M=MyLedger,profile=document.querySelector('#profileForm'),settings=document.querySelector('#settingsForm'),password=document.querySelector('#passwordForm'),audit=document.querySelector('#auditList');try{const [d,a]=await Promise.all([M.request('/ajax/settings'),M.request('/ajax/audit-log?per_page=10')]);settings.theme.value=d.theme||'system';settings.locale.value=d.locale||'en';settings.daily_reminder_time.value=d.daily_reminder_time?String(d.daily_reminder_time).slice(0,5):'';audit.innerHTML=a.data.length?a.data.map(x=>`<div class="d-flex justify-content-between gap-3 py-2 border-bottom"><div><div class="small fw-semibold text-capitalize">${M.esc(x.action)}</div><div class="small text-secondary">${M.esc(x.new_values?.reference_no||x.auditable_type.split('\\').pop())}</div></div><div class="small text-secondary text-nowrap">${M.dateTime(x.created_at)}</div></div>`).join(''):'<div class="small text-secondary">No accounting changes yet.</div>'}catch(e){M.toast(e.message,'danger')}profile.onsubmit=async e=>{e.preventDefault();try{await M.request('/ajax/profile',{method:'PATCH',body:JSON.stringify(M.payload(profile))});M.toast('Profile updated.')}catch(err){M.errors(profile,err)}};settings.onsubmit=async e=>{e.preventDefault();try{const d=await M.request('/ajax/settings',{method:'PATCH',body:JSON.stringify(M.payload(settings))});M.toast('Preferences saved.');document.documentElement.dataset.themePreference=d.theme||'system';const dark=d.theme==='dark'||(d.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.setAttribute('data-bs-theme',dark?'dark':'light')}catch(err){M.errors(settings,err)}};password.onsubmit=async e=>{e.preventDefault();try{await M.request('/ajax/profile/password',{method:'PUT',body:JSON.stringify(M.payload(password))});password.reset();M.toast('Password updated.')}catch(err){M.errors(password,err)}}})();
</script>
@endpush
